In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [3]:
x= np.ones(3)
x

array([1., 1., 1.])

## Q#2: Create y array with elements equal to 0.

In [4]:
y = np.zeros(3)
y

array([0., 0., 0.])

## Q#3: Add x and y arrays.

In [5]:
Addition= x + y
Addition

array([1., 1., 1.])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [6]:
print("type: ",x.dtype)
print("shape: ",x.shape)
print("dimansions: ",x.ndim)
print("size: ",x.size)

type:  float64
shape:  (3,)
dimansions:  1
size:  3


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [7]:
w = np.array([[11, 12],
              [13, 14],
              [15, 16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [8]:
z = np.arange(1,4)
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [9]:
z_reshaped = z.reshape(-1, 1)
newArray = np.hstack((z_reshaped, w))
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [10]:
for elemment in newArray:
    print(elemment)

[ 1 11 12]
[ 2 13 14]
[ 3 15 16]


## Q#9: Reverse the columns and rows of "newArray".

In [11]:
reversedArray = newArray[::-1, ::-1]
reversedArray

array([[16, 15,  3],
       [14, 13,  2],
       [12, 11,  1]])

## Q#10: Decrement all elements of "newArray" with 1.

In [12]:
de=newArray-1
de

array([[ 0, 10, 11],
       [ 1, 12, 13],
       [ 2, 14, 15]])

## Q#11: Find smallest and biggest values in "newArray".

In [13]:
smallna=np.min(newArray)
bigna=np.max(newArray)
print("the smallest value in newArray: ",smallna)
print("the biggest value in newArray: ",bigna)

the smallest value in newArray:  1
the biggest value in newArray:  16


## Q#12: Print the first row of "newArray" using indexing.

In [14]:
newArray[0]

array([ 1, 11, 12])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [19]:
number_12= de[1,1]
print(number_12)

12


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [26]:
number0 = de[0, 0]
number13=de[1,2]
print(number0)
print(number13)

0
13


## Q#15: Change the shape of "newArray" to (9,1).

In [28]:
reshapArr = de.reshape(9, 1)
reshapArr

array([[ 0],
       [10],
       [11],
       [ 1],
       [12],
       [13],
       [ 2],
       [14],
       [15]])

## Q#16: Change the shape of "newArray" to (3,2).

In [35]:
reshapArr1 = de.flatten()[:6].reshape(3, 2)
reshapArr1

array([[ 0, 10],
       [11,  1],
       [12, 13]])

# Well Done 🎉